# Generated by Django 2.2.6 on 2022-08-23 10:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('this_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(default='', max_length=150)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('this_id', models.AutoField(primary_key=True, serialize=False)),
                ('allitems', models.CharField(max_length=1000)),
                ('amount', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=500)),
                ('address_line2', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('zip_code', models.CharField(max_length=6)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 8, 23, 10, 15, 1, 234316))),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('this_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_Id', models.CharField(max_length=20)),
                ('update_desc', models.CharField(max_length=3000)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 8, 23, 10, 15, 1, 234707))),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('this_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=100)),
                ('sub_category', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('price', models.IntegerField(default=0)),
                ('discount', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('this_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4000)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.CharField(max_length=4000)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
    ]
