# Generated by Django 2.2.6 on 2022-08-25 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20220825_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 8, 5, 59, 712644)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 8, 5, 59, 713026)),
        ),
    ]
