# Generated by Django 2.2.6 on 2022-08-25 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20220825_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='amount',
            new_name='promo_amount',
        ),
        migrations.RenameField(
            model_name='promocode',
            old_name='code',
            new_name='promo_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 8, 7, 32, 210769)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 8, 7, 32, 211173)),
        ),
    ]
