# Generated by Django 2.2.6 on 2022-08-25 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20220825_0807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 8, 8, 35, 977246)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 8, 8, 35, 977632)),
        ),
    ]
