# Generated by Django 2.2.6 on 2022-08-25 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20220825_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_amt', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 9, 39, 59, 800126)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 9, 39, 59, 800516)),
        ),
    ]
