# Generated by Django 2.2.6 on 2022-08-26 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20220825_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='update_choice',
            field=models.CharField(choices=[('Your order has been successfully placed.', '1'), ('Your order reached at ', '2'), ('Your order has been successfully delivered.', '3')], default='1', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 7, 40, 24, 467609)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 7, 40, 24, 468048)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(max_length=200),
        ),
    ]
