# Generated by Django 2.2.6 on 2022-08-26 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20220826_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='payment_status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 7, 44, 37, 872891)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 7, 44, 37, 873345)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='update_choice',
            field=models.CharField(choices=[('1', 'Your order has been successfully placed.'), ('2', 'Your order reached at '), ('3', 'Your order has been successfully delivered.')], default='1', max_length=500),
        ),
    ]
