# Generated by Django 2.2.6 on 2022-08-26 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20220826_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 8, 7, 2, 920764)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 8, 7, 2, 921225)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='update_choice',
            field=models.CharField(choices=[('Your order has been successfully placed.', 'Your order has been successfully placed.'), ('Your order has been picked by courier.', 'Your order has been picked by courier.'), ('Your order reached at ', 'Your order reached at '), ('Your order has been successfully delivered.', 'Your order has been successfully delivered.')], default='Your order has been successfully placed.', max_length=500),
        ),
    ]
