# Generated by Django 2.2.6 on 2022-08-29 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20220826_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 5, 41, 14, 294616)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 5, 41, 14, 295064)),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=''),
        ),
    ]
