# Generated by Django 4.1 on 2022-10-21 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20220829_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='allitems',
        ),
        migrations.AddField(
            model_name='order',
            name='items_id',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extra_fields',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 3, 49, 37, 624330)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 3, 49, 37, 624614)),
        ),
    ]
