# Generated by Django 4.1 on 2022-10-21 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_product_audio_jack_product_battery_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proccessor',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 6, 25, 1, 40844)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 6, 25, 1, 41124)),
        ),
    ]
