# Generated by Django 4.1 on 2022-10-28 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_extra_fields_phone_alter_order_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_fields',
            name='addrs_l1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='extra_fields',
            name='addrs_l2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='extra_fields',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='extra_fields',
            name='pin_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='extra_fields',
            name='state',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 6, 57, 17, 93538)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 6, 57, 17, 93813)),
        ),
    ]
